{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: portainer-edge-creds
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  edge-id: {{ .Values.edgeId | quote }}
  edge-key: {{ .Values.edgeKey | quote }}
{{- end }}

